 VitisRTLKernel sdpmm(
    .ap_clk          ( ap_clk          ),
    .ap_start        ( ap_start        ),
    .ap_done         ( ap_done         ),
    .ap_idle         ( ap_idle         ),
    .ap_ready        ( ap_ready        ),

    .dataIF_inputNumTimes (inputTimes),

    .dataIF_pipeReadLength            ( pipeReadLength      ),
    .dataIF_pipeReadAddress           ( pipeReadAddress     ),
    .dataIF_pipeWriteAddress          ( pipeWriteAddress    ),
    .dataIF_m00Read_ar_ready      (m00_axi_arready),
    .dataIF_m00Read_ar_valid      (m00_axi_arvalid),
    .dataIF_m00Read_ar_bits_addr  (m00_axi_araddr),
    .dataIF_m00Read_ar_bits_len   (m00_axi_arlen),
    .dataIF_m00Read_r_ready       (m00_axi_rready),
    .dataIF_m00Read_r_valid       (m00_axi_rvalid),
    .dataIF_m00Read_r_bits_data   (m00_axi_rdata),
    .dataIF_m00Read_r_bits_last   (m00_axi_rlast),
    .dataIF_m00Write_aw_ready     (m00_axi_awready),
    .dataIF_m00Write_aw_valid     (m00_axi_awvalid),
    .dataIF_m00Write_aw_bits_addr (m00_axi_awaddr),
    .dataIF_m00Write_aw_bits_len  (m00_axi_awlen),
    .dataIF_m00Write_w_ready      (m00_axi_wready),
    .dataIF_m00Write_w_valid      (m00_axi_wvalid),
    .dataIF_m00Write_w_bits_data  (m00_axi_wdata),
    .dataIF_m00Write_w_bits_strb  (m00_axi_wstrb),
    .dataIF_m00Write_w_bits_last  (m00_axi_wlast),
    .dataIF_m00Write_b_ready      (m00_axi_bready),
    .dataIF_m00Write_b_valid      (m00_axi_bvalid),

    .dataIF_kReadLength            ( kReadLength      ),
    .dataIF_kReadAddress           ( kReadAddress     ),
    .dataIF_kWriteAddress          ( kWriteAddress    ),
    .dataIF_m01Read_ar_ready      (m01_axi_arready),
    .dataIF_m01Read_ar_valid      (m01_axi_arvalid),
    .dataIF_m01Read_ar_bits_addr  (m01_axi_araddr),
    .dataIF_m01Read_ar_bits_len   (m01_axi_arlen),
    .dataIF_m01Read_r_ready       (m01_axi_rready),
    .dataIF_m01Read_r_valid       (m01_axi_rvalid),
    .dataIF_m01Read_r_bits_data   (m01_axi_rdata),
    .dataIF_m01Read_r_bits_last   (m01_axi_rlast),
    .dataIF_m01Write_aw_ready     (m01_axi_awready),
    .dataIF_m01Write_aw_valid     (m01_axi_awvalid),
    .dataIF_m01Write_aw_bits_addr (m01_axi_awaddr),
    .dataIF_m01Write_aw_bits_len  (m01_axi_awlen),
    .dataIF_m01Write_w_ready      (m01_axi_wready),
    .dataIF_m01Write_w_valid      (m01_axi_wvalid),
    .dataIF_m01Write_w_bits_data  (m01_axi_wdata),
    .dataIF_m01Write_w_bits_strb  (m01_axi_wstrb),
    .dataIF_m01Write_w_bits_last  (m01_axi_wlast),
    .dataIF_m01Write_b_ready      (m01_axi_bready),
    .dataIF_m01Write_b_valid      (m01_axi_bvalid),

    .dataIF_vReadLength            ( vReadLength      ),
    .dataIF_vReadAddress           ( vReadAddress     ),
    .dataIF_vWriteAddress          ( vWriteAddress    ),
    .dataIF_m02Read_ar_ready      (m02_axi_arready),
    .dataIF_m02Read_ar_valid      (m02_axi_arvalid),
    .dataIF_m02Read_ar_bits_addr  (m02_axi_araddr),
    .dataIF_m02Read_ar_bits_len   (m02_axi_arlen),
    .dataIF_m02Read_r_ready       (m02_axi_rready),
    .dataIF_m02Read_r_valid       (m02_axi_rvalid),
    .dataIF_m02Read_r_bits_data   (m02_axi_rdata),
    .dataIF_m02Read_r_bits_last   (m02_axi_rlast),
    .dataIF_m02Write_aw_ready     (m02_axi_awready),
    .dataIF_m02Write_aw_valid     (m02_axi_awvalid),
    .dataIF_m02Write_aw_bits_addr (m02_axi_awaddr),
    .dataIF_m02Write_aw_bits_len  (m02_axi_awlen),
    .dataIF_m02Write_w_ready      (m02_axi_wready),
    .dataIF_m02Write_w_valid      (m02_axi_wvalid),
    .dataIF_m02Write_w_bits_data  (m02_axi_wdata),
    .dataIF_m02Write_w_bits_strb  (m02_axi_wstrb),
    .dataIF_m02Write_w_bits_last  (m02_axi_wlast),
    .dataIF_m02Write_b_ready      (m02_axi_bready),
    .dataIF_m02Write_b_valid      (m02_axi_bvalid)
  );